<a href="https://colab.research.google.com/github/Tezcan32/cognitivetrack/blob/main/notebooks/01_python_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
df.head()
df["age_group"] = df["age"] >= 70
df.head()
df.groupby("age")["age_group"].mean()

age
65    0.0
67    0.0
72    1.0
74    1.0
80    1.0
Name: age_group, dtype: float64

In [ ]:
# Yaşı 70 ve üzerinde olan katılımcıları filtreleyelim
age_over_70 = df[df["age"] >= 70]
display(age_over_70)

In [ ]:
import numpy as np

# Eğer yaş 70'ten büyük veya eşitse kendi yaşını yaz, değilse NaN (boş) bırak
df["age_over_70_values"] = np.where(df["age"] >= 70, df["age"], np.nan)

display(df)

In [15]:
# Yöntem 1: .loc kullanarak (numpy olmadan)
df["age_over_70_values"] = None
df.loc[df["age"] >= 70, "age_over_70_values"] = df["age"]

display(df)

# tmt_time değeri 50'den küçük olan satırların tmt_time ortalaması:
filtered_mean = df[df["tmt_time"] < 50]["tmt_time"].mean()
print("TMT Time < 50 olanların ortalaması:", filtered_mean)

df.groupby("age")["age_over_70_values"].mean()

,participant,age,tmt_time,errors,sleep_hours,age_group,age_over_70_values
0,P01,67,45.2,1,7.2,False,None
1,P02,72,61.3,2,6.1,True,72
2,P03,65,39.8,0,8.0,False,None
3,P04,80,72.1,3,5.5,True,80
4,P05,74,55.4,1,7.0,True,74

TMT Time < 50 olanların ortalaması: 42.5

age
65     NaN
67     NaN
72    72.0
74    74.0
80    80.0
Name: age_over_70_values, dtype: object